## Creating Tensors

We can create tensors with `tf.constant()` method.

There is another way of doing it by using `tf.Variable()`.

We can create a random tensor by using `tf.random.uniform(shape=())`

We can use `tf.random.shuffle()` to shuffle the order of our tensor.

You can research about the `seed`s the global and operational one in tensorflow documentation.


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[10,7,],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Manipulatr the datatype of tensor
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create tensors with tf.Variable()

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's change one element of our changeable_tensor variable

changeable_tensor[0] = 10
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# We could just look the documentation and see that how this class is working
# By visit the web page we can see that there is a method .assign() for changing it
# We cannot change the elements of tf.constant() object

changeable_tensor[0].assign(8)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

In [ ]:
# Creating a random tensore and think about the equality of them

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 , random_2 , random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# As you can see the random is just a placeholder it is not "random" in the right sense because by having a same shape and seed
# the value would be the same
# So now let's create a shuffled version of that.

not_shuffled = tf.constant([[10,7],
                             [3,4],
                             [2,5]])
tf.random.set_seed(42) # This is a global seed
tf.random.shuffle(not_shuffled, seed=42) # This is an operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Indexing and Accessing a Tensor

We can use python indexing to access the element(s) of a tensor.

We can use `tf.newaxis` to add new axis to our tensor like below:

Alternative to newaxis method is `tf.expand_dims()`

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.zeros(shape=[2,3])
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]], dtype=float32)>

### Manipulating a Tensor



In [ ]:
import numpy as np

In [ ]:
E = tf.constant(np.random.randint(0,100,50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([89, 66,  7, 35, 55, 55, 89,  7,  7, 71, 67, 61, 23, 99, 34, 91, 23,
       28, 39, 43,  0, 13, 96, 36, 65, 17, 97, 60, 99, 89, 69,  5, 93, 38,
       23, 33, 50,  9, 73, 72, 84, 41, 29, 51, 56, 63,  3,  3, 45, 54])>

In [ ]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)


<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(E)


<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [ ]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2455>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.84644>

In [ ]:
tf.math.pow(tf.math.reduce_std(tf.cast(E, dtype=tf.float32)), 2)

<tf.Tensor: shape=(), dtype=float32, numpy=890.80994>